name: 'Terraform_Deploy_Azure'

on:
  push:
    branches:
    - "test"
  pull_request:
    branches:
    - "test"
  workflow_dispatch: #for manual run


env:
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  ARM_ACCESS_KEY: ${{secrets.AZURE_STORAGE_ACCOUNT_KEY}}

jobs:
  terraform_plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Checkout
      uses: actions/checkout@v3


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      working-directory: /env/${{ steps.extract_branch.outputs.branch }}
      run: terraform init
      env:
        TF_VAR_current_branch_name : ${{ steps.extract_branch.outputs.branch }}

    - name: Terraform Plan
      working-directory: /env/${{ steps.extract_branch.outputs.branch }}
      run: terraform plan -input=false
      env:
        TF_VAR_current_branch_name : ${{ steps.extract_branch.outputs.branch }}



  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: dev
    needs: [terraform_plan]

    defaults:
      run:
        shell: bash

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      working-directory: /env/${{ steps.extract_branch.outputs.branch }}
      run: terraform init
      env:
        TF_VAR_current_branch_name : ${{ steps.extract_branch.outputs.branch }}


    - name: Terraform Apply
      working-directory: /env/${{ steps.extract_branch.outputs.branch }}
      run: terraform apply -auto-approve #-input=false
      env:
        TF_VAR_current_branch_name : ${{ steps.extract_branch.outputs.branch }}